[package]
name = "tokio-zookeeper"
version = "0.1.0"
authors = ["Jon Gjengset <jon@thesquareplanet.com>"]

[dependencies]
futures = "0.1"
tokio = "0.1"
failure = "0.1"
byteorder = "1.2"
lazy_static = "1.0"
slog = "2.3.2"
#slog = { version = "2.3.2", features = ['max_level_trace'] }

[dev-dependencies]
slog-async = "2.3.0"
slog-term = "2.4.0"
